// Generated by CoffeeScript 1.3.3
(function() {
  var render_twitter, show_twitter, twitter_template;

  twitter_template = Handlebars.compile($("#twitter-template").html());

  render_twitter = function(data) {
    var context, modal;
    context = {
      user: {
        name: data[0].user.name,
        screen_name: data[0].user.screen_name,
        profile_image_url: data[0].user.profile_image_url,
        f_description: data[0].user.description,
        location: data[0].user.location,
        url: data[0].user.url,
        statuses_count: data[0].user.statuses_count,
        friends_count: data[0].user.friends_count,
        followers_count: data[0].user.followers_count
      },
      tweets: data
    };
    modal = $(twitter_template(context));
    $("body").append(modal);
    return modal.modal('show');
  };

  show_twitter = function() {
    var twitter_modal;
    twitter_modal = $(".twitter.modal");
    if (twitter_modal.length) {
      return twitter_modal.modal('show');
    }
    return $.ajax({
      url: "http://api.twitter.com/1/statuses/user_timeline.json?include_rts=true&screen_name=adamjacobbecker",
      dataType: "jsonp",
      success: render_twitter
    });
  };

  $(document).on("click", "#twitter-link", show_twitter);

}).call(this);
