// Generated by CoffeeScript 1.3.3
(function() {
  var close_all_modals, first_active, github_template, render_github, render_twitter, reset_active_nav, set_active_nav, show_github, show_twitter, twitter_template;

  twitter_template = false;

  github_template = false;

  close_all_modals = function() {
    return $(".modal").modal('hide');
  };

  render_twitter = function(data) {
    var context, modal;
    context = {
      user: {
        name: data[0].user.name,
        screen_name: data[0].user.screen_name,
        profile_image_url: data[0].user.profile_image_url,
        f_description: data[0].user.description,
        location: data[0].user.location,
        url: data[0].user.url,
        statuses_count: data[0].user.statuses_count,
        friends_count: data[0].user.friends_count,
        followers_count: data[0].user.followers_count
      },
      tweets: data
    };
    modal = $(twitter_template(context));
    $("body").append(modal);
    close_all_modals();
    return modal.modal('show');
  };

  render_github = function(user_data, repo_data) {
    var context, modal;
    context = {
      user: user_data,
      repos: repo_data
    };
    modal = $(github_template(context));
    $("body").append(modal);
    close_all_modals();
    return modal.modal('show');
  };

  show_twitter = function() {
    var twitter_modal;
    twitter_modal = $(".twitter.modal");
    if (twitter_modal.length) {
      close_all_modals();
      return twitter_modal.modal('show');
    }
    return $.ajax({
      url: "{{site.url}}/templates/twitter.tpl",
      success: function(data) {
        twitter_template = Handlebars.compile(data);
        return $.ajax({
          url: "http://api.twitter.com/1/statuses/user_timeline.json?include_rts=true&screen_name={{site.twitter}}",
          dataType: "jsonp",
          success: render_twitter
        });
      }
    });
  };

  show_github = function() {
    var github_modal;
    github_modal = $(".github.modal");
    if (github_modal.length) {
      close_all_modals();
      return github_modal.modal('show');
    }
    return $.ajax({
      url: "{{site.url}}/templates/github.tpl",
      success: function(data) {
        github_template = Handlebars.compile(data);
        return $.ajax({
          url: "https://api.github.com/users/{{site.github}}",
          dataType: "json",
          success: function(user_data) {
            return $.ajax({
              url: "https://api.github.com/users/{{site.github}}/repos",
              dataType: "json",
              success: function(repo_data) {
                return render_github(user_data, repo_data);
              }
            });
          }
        });
      }
    });
  };

  first_active = false;

  set_active_nav = function(el) {
    var nav;
    nav = $("#links");
    if (!first_active) {
      first_active = nav.find("li.active");
    }
    nav.find("li").removeClass("active");
    return el.addClass("active");
  };

  reset_active_nav = function() {
    var nav;
    nav = $("#links");
    nav.find("li").removeClass("active");
    if (first_active) {
      return first_active.addClass("active");
    }
  };

  $(document).on("click", "#twitter-link", show_twitter);

  $(document).on("click", "#github-link", show_github);

  $(document).on("show", ".twitter.modal", function() {
    return set_active_nav($("#twitter-link").parent());
  });

  $(document).on("show", ".github.modal", function() {
    return set_active_nav($("#github-link").parent());
  });

  $(document).on("hide", ".profile.modal", function() {
    return reset_active_nav();
  });

}).call(this);
