// Generated by CoffeeScript 1.3.3
(function() {
  var first_active, render_twitter, reset_active_nav, set_active_nav, show_twitter, twitter_template;

  twitter_template = false;

  render_twitter = function(data) {
    var context, modal;
    context = {
      user: {
        name: data[0].user.name,
        screen_name: data[0].user.screen_name,
        profile_image_url: data[0].user.profile_image_url,
        f_description: data[0].user.description,
        location: data[0].user.location,
        url: data[0].user.url,
        statuses_count: data[0].user.statuses_count,
        friends_count: data[0].user.friends_count,
        followers_count: data[0].user.followers_count
      },
      tweets: data
    };
    modal = $(twitter_template(context));
    $("body").append(modal);
    return modal.modal('show');
  };

  show_twitter = function() {
    var twitter_modal;
    twitter_modal = $(".twitter.modal");
    if (twitter_modal.length) {
      return twitter_modal.modal('show');
    }
    return $.ajax({
      url: "{{site.url}}/templates/twitter.tpl",
      success: function(data) {
        twitter_template = Handlebars.compile(data);
        return $.ajax({
          url: "http://api.twitter.com/1/statuses/user_timeline.json?include_rts=true&screen_name=adamjacobbecker",
          dataType: "jsonp",
          success: render_twitter
        });
      }
    });
  };

  first_active = false;

  set_active_nav = function(el) {
    var nav;
    nav = $("#links");
    if (!first_active) {
      first_active = nav.find("li.active");
    }
    nav.find("li").removeClass("active");
    return el.addClass("active");
  };

  reset_active_nav = function() {
    var nav;
    nav = $("#links");
    nav.find("li").removeClass("active");
    return first_active.addClass("active");
  };

  $(document).on("click", "#twitter-link", show_twitter);

  $(document).on("show", ".twitter.modal", function() {
    return set_active_nav($("#twitter-link").parent());
  });

  $(document).on("hide", ".profile.modal", function() {
    return reset_active_nav();
  });

}).call(this);
